import type { Publication } from "@/lib/types";

// SAMPLE CONTENT — do not treat as real publications. Replace with the
// candidate's actual work before publishing the site. To add a new
// publication, copy an object below and fill in every field; omit `doi`,
// `venue`, or `links` keys you don't have rather than leaving them empty.
export const publications: Publication[] = [
  {
    slug: "intergenerational-variation-2025",
    title:
      "Intergenerational variation in Spanish subject pronoun expression among heritage speakers in the Midwest",
    authors: ["[FULL NAME]"],
    year: 2025,
    type: "journal-article",
    status: "published",
    venue: "[Journal Name]",
    abstract:
      "Sample abstract: this study examines rates of overt subject pronoun expression across three generations of Spanish heritage speakers, arguing that generational shifts reflect contact-induced restructuring rather than simple attrition.",
    keywords: ["heritage Spanish", "variation", "subject pronoun expression", "generational change"],
    themes: ["heritage-spanish-us", "variation-identity"],
    doi: "10.0000/placeholder.2025.01",
    links: { publisher: "#", pdf: "#" },
    peerReviewed: true,
    openAccess: false,
    language: "en",
    featured: true,
    selected: true,
  },
  {
    slug: "variation-identity-chapter-2024",
    title: "Dialect contact and identity construction among second-generation Mexican-American bilinguals",
    authors: ["[FULL NAME]", "[Co-author Name]"],
    year: 2024,
    type: "book-chapter",
    status: "published",
    venue: "[Edited Volume Title]",
    abstract:
      "Sample abstract: a discourse-analytic account of how second-generation bilinguals deploy regional variants to index belonging within and across dialect communities.",
    keywords: ["dialect contact", "identity", "discourse analysis"],
    themes: ["variation-identity"],
    links: { publisher: "#" },
    peerReviewed: true,
    openAccess: false,
    language: "en",
    selected: true,
  },
  {
    slug: "raciolinguistic-ideologies-2023",
    title: "\u201CYou don't sound Mexican\u201D: raciolinguistic ideologies in heritage speaker self-narratives",
    authors: ["[FULL NAME]"],
    year: 2023,
    type: "journal-article",
    status: "published",
    venue: "[Journal Name]",
    abstract:
      "Sample abstract: drawing on sociolinguistic interviews, this article traces how heritage speakers narrate experiences of being racialized through speech and how they contest deficit framings of their bilingualism.",
    keywords: ["raciolinguistics", "language ideology", "narrative"],
    themes: ["raciolinguistics"],
    doi: "10.0000/placeholder.2023.04",
    links: { pdf: "#", repository: "#" },
    peerReviewed: true,
    openAccess: true,
    language: "en",
    selected: true,
  },
  {
    slug: "policy-brief-2026",
    title: "Supporting heritage Spanish speakers in K-12 dual-language programs: a policy brief",
    authors: ["[FULL NAME]"],
    year: 2026,
    type: "policy-brief",
    status: "forthcoming",
    abstract:
      "Sample abstract: recommendations for placement, assessment, and curriculum design that avoid deficit-based treatment of heritage learners in dual-language programs.",
    keywords: ["policy", "dual-language education", "heritage learners"],
    themes: ["heritage-education", "language-policy-justice"],
    peerReviewed: false,
    openAccess: true,
    language: "en",
  },
  {
    slug: "manuscript-under-review-2026",
    title: "Translanguaging as pedagogy: a classroom ethnography in a heritage Spanish course",
    authors: ["[FULL NAME]"],
    year: 2026,
    type: "manuscript-under-review",
    status: "under-review",
    abstract:
      "Sample abstract: a classroom ethnography documenting how an instructor's translanguaging pedagogy shaped students' metalinguistic awareness and confidence.",
    keywords: ["translanguaging", "pedagogy", "classroom ethnography"],
    themes: ["translanguaging", "heritage-education"],
    peerReviewed: false,
    openAccess: false,
    language: "en",
  },
  {
    slug: "articulo-divulgacion-2025",
    title: "El español que hablamos en casa: por qué toda variedad tiene valor",
    authors: ["[NOMBRE COMPLETO]"],
    year: 2025,
    type: "public-scholarship",
    status: "published",
    venue: "[Medio de divulgación]",
    abstract:
      "Resumen de muestra: un artículo de divulgación dirigido a familias bilingües sobre la legitimidad lingüística de las variedades del español de herencia.",
    keywords: ["divulgación", "español de herencia", "familias bilingües"],
    themes: ["heritage-spanish-us", "community-engaged-research"],
    links: { publisher: "#" },
    peerReviewed: false,
    openAccess: true,
    language: "es",
  },
];
